# defaults:
#   - override /model: default
defaults:
  - /model/default 

model_id: augment
equivariance: Tn               # Type of equivariance
orientations: 0                # Number of orientations
train_augm: true               # Apply augmentation during training
scalar_features: []            # Features to use as scalars
vector_features: []            # Features to use as vectors