# defaults:
#   - override /model: default
defaults:
  - /model/default 

model_id: equivariant
equivariance: SEn              # Type of equivariance
orientations: 8                # Number of orientations
train_augm: true               # Apply augmentation during training
scalar_features: []            # Features to use as scalars
vector_features: []            # Features to use as vectors
